"""
BBIBOLL策略回测示例 - 使用新的回测框架
"""

import os

import polars as pl

from backtesting.backtest_pre_data import load_spx_benchmark, only_common_stocks
from backtesting.engine import BacktestEngine
from backtesting.visualizer import BacktestVisualizer
from core_2.config import all_tickers_dir
from core_2.data_loader import stock_load_process


def run_backtest(strategy, strategy_config=None):
    """MAIN BACKTEST PROCESSION"""

    print("Load data...")
    tickers = only_common_stocks(filter_date=strategy_config["data_start_date"])

    try:
        ohlcv_data = (
            stock_load_process(
                tickers=tickers.to_series().to_list(),
                timeframe=strategy_config["timeframe"],
                start_date=strategy_config["data_start_date"],
                end_date=strategy_config["end_date"],
                # use_cache=False,
            )
            .filter(pl.col("volume") != 0)
            .collect()
        )

        print(f"tickers number: {ohlcv_data.select('ticker').n_unique()}")

    except Exception as e:
        print(f"data load failed: {e}")
        return

    print("load benchmark data...")
    benchmark_data = load_spx_benchmark(
        strategy_config["trade_start_date"], strategy_config["end_date"]
    )

    engine = BacktestEngine(initial_capital=strategy_config["initial_capital"])

    engine.add_strategy(strategy, ohlcv_data, tickers)

    print("start backtest...")
    results = engine.run_backtest(
        strategy=strategy,
        benchmark_data=benchmark_data,
        save_results=True,
        # use_cached_indicators=True,
    )

    strategy_name = strategy.name
    output_dir = os.path.join(
        "backtest_output",
        strategy_name,
        strategy_config.get("result_customized_name", ""),
    )
    os.makedirs(output_dir, exist_ok=True)

    print("generating backtest plot...")
    selected_ticker = strategy_config["selected_tickers"][0]
    try:
        if (
            len(strategy_config.get("selected_tickers", [])) > 1
            or selected_ticker == "random"
        ):
            engine.plot_results(
                strategy_name=strategy_name,
                plot_equity=True,
                plot_performance=True,
                plot_monthly=True,
                save_plots=True,
                output_dir=output_dir,
            )

        visualizer = BacktestVisualizer()

        if (
            len(strategy_config.get("selected_tickers", [])) > 1
            or selected_ticker == "random"
        ) and (strategy_config["plot_all"] == False):
            selected_ticker = (
                results["trades"].select("ticker").unique().to_series().sample(1)[0]
            )
            print(f"plot {selected_ticker} k-line and trade signal...")
            visualizer.plot_candlestick_with_signals(
                ohlcv_data=ohlcv_data,
                trades=results["trades"],
                ticker=selected_ticker,
                start_date=strategy_config["trade_start_date"],
                end_date=strategy_config["end_date"],
                indicators=results.get("indicators"),
                # line=False,
                save_path=f"{output_dir}/{selected_ticker}_signals.png",
            )

        elif strategy_config["plot_all"]:
            for selected_ticker in strategy_config.get("selected_tickers", []):
                print(f"plot {selected_ticker} k-line and trade signal...")
                visualizer.plot_candlestick_with_signals(
                    ohlcv_data=ohlcv_data,
                    trades=results["trades"],
                    ticker=selected_ticker,
                    start_date=strategy_config["trade_start_date"],
                    end_date=strategy_config["end_date"],
                    indicators=results.get("indicators"),
                    line=False,
                    save_path=f"{output_dir}/{selected_ticker}_signals.png",
                )

    except Exception as e:
        print(f"error occurs during plotting: {e}")

    print("export backtest result...")
    try:
        engine.export_results(strategy_config, strategy_name, output_dir=output_dir)
    except Exception as e:
        print(f"backtest result export failed: {e}")

    print("\n关键结果摘要:")
    print("-" * 40)
    performance = results["performance_metrics"]

    key_metrics = [
        ("Total Return [%]", f"{performance.get('Total Return [%]', 0):.2f}%"),
        ("Benchmark Return [%]", f"{performance.get('Benchmark Return [%]', 0):.2f}%"),
        ("Max Drawdown [%]", f"{performance.get('Max Drawdown [%]', 0):.2f}%"),
        ("Sharpe Ratio", f"{performance.get('Sharpe Ratio', 0):.4f}"),
        ("Win Rate [%]", f"{performance.get('Win Rate [%]', 0):.2f}%"),
        ("Total Trades", f"{performance.get('Total Trades', 0)}"),
    ]

    for metric, value in key_metrics:
        print(f"{metric:<12}: {value}")

    print(f"\nBacktest done! result isexported to {output_dir}")


if __name__ == "__main__":
    from strategies.bbibollStrategy import BBIBOLLStrategy

    print("BBIBOLL Strategy Backtest")
    print("=" * 60)

    strategy_config = {
        "result_customized_name": "recently",  # distinguish different config runs
        "boll_length": 11,
        "boll_multiple": 6,
        "max_dev_pct": 1,
        "loss_threshold": -0.15,
        "profit_threshold": 0.1,
        # "selected_tickers": ["SFE"],
        "selected_tickers": [
            "LGPS",
            "INHD",
            "DFLI",
            "IBG",
            "BON",
            "PRFX",
            "JBDI",
            "BLMZ",
            "PRSO",
            "DNUT",
            "NBY",
            "VRME",
            "ETNB",
            "MNTS",
            "STKH",
            "WBD",
            "VERI",
            "XPON",
            "VSME",
            "AQB",
            "PBM",
            "WOLF",
            "TLS",
            "ORIS",
            "WULF",
            "MWYN",
            "ATCH",
            "HXHX",
            "CMND",
            "STAI",
            "MEG",
            "SKBL",
            "CGC",
            "BIYA",
            "SBEV",
            "CDLX",
            "PLUG",
            "MGX",
            "CNTX",
            "QNRX",
            "WAI",
            "NAMI",
            "HTCO",
            "RDZN",
            "CVM",
            "VCIG",
            "RCKT",
            "WST",
            "WAFU",
            "BRFH",
            "LSH",
            "BRZE",
            "PHIO",
            "NWTG",
            "KIDZ",
            "MGIH",
            "NCNA",
            "MOGU",
            "HOLO",
            "MAPS",
            "SPPL",
            "FLXS",
            "DOCN",
            "ZSPC",
            "BEAT",
            "SONM",
            "AMCX",
            "NRIX",
            "BTDR",
            "MCTR",
            "MCRP",
            "GRO",
            "TOP",
            "CRBP",
            "NAMM",
            "SKBL",
            "RAYA",
            "ENGS",
            "AEO",
            "GSIW",
            "GIBO",
            "SVRE",
            "UPLD",
            "TAOP",
            "ESTC",
            "ABP",
            "MSW",
            "GWAV",
            "INHD",
            "NTCL",
            "VIAV",
            "DFLI",
            "ATXG",
            "ABSI",
            "DAKT",
            "ZJYL",
            "SDOT",
            "MTSR",
            "GELS",
            "WYHG",
            "IMPP",
            "LRE",
            "VRA",
            "RAYA",
            "KRRO",
            "APRE",
            "PLRZ",
            "GIBO",
            "YTRA",
            "STTK",
            "JYD",
            "HTCR",
            "NISN",
            "BARK",
            "SDA",
            "AVR",
            "AZI",
            "ANIX",
            "BNGO",
            "WNW",
            "PSNL",
            "AIRE",
            "XXII",
            "UGRO",
            "PETZ",
            "AEYE",
            "RDGT",
            "HBIO",
            "CMND",
            "MGX",
            "BYND",
            "ORBS",
            "LUNG",
            "XFOR",
            "APDN",
            "SNWV",
            "CADL",
            "ADVB",
            "WB",
            "TGL",
            "NBIS",
            "PRLD",
            "COOT",
            "IONR",
            "PHOE",
            "LDWY",
            "UONEK",
            "ANY",
            "ZBAI",
            "MPW",
            "MCTR",
            "GDHG",
            "TER",
            "EXOZ",
            "AFRI",
            "BIAF",
            "HUMA",
            "DBRG",
            "TCRX",
            "BMNR",
            "DYN",
            "CDTG",
            "KRRO",
            "ARQ",
            "AMIX",
            "YSXT",
            "CTNT",
            "PPBT",
            "PTNM",
            "TOYO",
            "RANI",
            "FGEN",
            "INFU",
            "KURA",
            "IRBT",
            "NVX",
            "VIR",
            "REVB",
            "MAAS",
            "DXST",
            "PRPH",
            "WGRX",
            "BCAB",
            "BENF",
            "REBN",
            "DXLG",
            "CETX",
            "MQ",
            "KALV",
            "SHO",
            "IQ",
            "TPST",
            "SGMO",
            "ALUR",
            "IBRX",
            "GLUE",
            "NDLS",
            "TARS",
            "SNBR",
            "WIMI",
            "HTCO",
            "HCAI",
            "NERV",
            "SVRE",
            "TLPH",
            "XRX",
            "HAIN",
            "SCHL",
            "CRBP",
            "GRDN",
            "FTRE",
            "MKZR",
            "PSNY",
            "EOSE",
            "NNVC",
            "ANNX",
            "ALZN",
            "RDHL",
            "POAI",
            "PLRZ",
            "HDSN",
            "MEGL",
            "JKS",
            "HOLO",
            "IONS",
            "INTS",
            "PRTA",
            "CTXR",
            "TOVX",
            "BW",
            "MLGO",
            "MKZR",
            "IOTR",
            "PLRX",
            "MI",
            "STRO",
            "AXR",
            "TMDE",
            "BCDA",
            "TWNP",
            "IRWD",
            "CMPS",
            "LSB",
            "PIII",
            "LXRX",
            "LGPS",
            "TTNP",
            "SST",
            "MTC",
            "WFF",
            "SUUN",
            "ELUT",
            "QH",
            "WLFC",
            "JAGX",
            "CCCC",
            "ALMU",
            "OLMA",
            "SOTK",
            "TNMG",
            "WTTR",
            "USLM",
            "HIPO",
            "PETS",
            "FBIO",
            "SEED",
            "ATOS",
            "PTON",
            "UOKA",
            "CENX",
            "WINA",
            "FATE",
            "HSII",
            "SORA",
            "AMKR",
            "FORR",
            "REE",
            "SITM",
            "IXHL",
            "KLRS",
            "ANGI",
            "SLE",
            "REI",
            "PAM",
            "VNO",
            "TRIB",
            "NGVT",
            "KTCC",
            "SMX",
            "HYFM",
            "MPWR",
            "UDMY",
            "SKYE",
            "NGL",
            "NTCL",
            "EONR",
            "MVIS",
            "ASBP",
            "SAFX",
            "CTGO",
            "ADVB",
            "HKIT",
            "ERNA",
            "BENF",
            "SSII",
            "QVCGA",
            "CETY",
            "LICN",
            "DVLT",
            "ATLX",
            "GDOT",
            "NSSC",
            "SYRE",
            "MOVE",
            "SLXN",
            "SMSI",
            "AVTX",
            "EKSO",
            "MEOH",
            "HWBK",
            "AGMH",
            "BMEA",
            "CENN",
            "RDI",
            "CRNT",
            "HMY",
            "ARQT",
            "EMBC",
            "MDIA",
            "CMTL",
            "OCGN",
            "IONR",
            "RDGT",
            "IDYA",
            "LUNG",
            "SILO",
            "HAO",
            "OMH",
            "BB",
            "CNCK",
            "ABEO",
            "SDOT",
            "ZNTL",
            "SGLY",
            "XNCR",
            "ARL",
            "RVSN",
            "NAT",
            "YQ",
            "PYPD",
            "LFWD",
            "PTNM",
            "ALMU",
            "DGLY",
            "HIND",
            "RVYL",
            "OGEN",
            "REGN",
            "MOBX",
            "STGW",
            "APPS",
            "ALXO",
            "ORKA",
            "JVA",
            "GIFI",
            "RIVN",
            "REPL",
            "IOVA",
            "FDMT",
            "AUST",
            "DAO",
            "CLWT",
            "ALTO",
            "SOWG",
            "CTNT",
            "ARWR",
            "CCTG",
            "SAGT",
            "FATN",
            "GIBO",
            "BIDU",
            "BTMD",
            "POWL",
            "GBCI",
            "FRPT",
            "SNWV",
            "HTCO",
            "ELBM",
            "YCBD",
            "ASTH",
            "BBIO",
            "BLIV",
            "ITT",
            "YXT",
            "COLB",
            "MBI",
            "PYXS",
            "APPS",
            "CEVA",
            "NFGC",
            "ABCB",
            "ONL",
            "HTOO",
            "IRD",
            "LTRN",
            "LWLG",
            "ECO",
            "EHGO",
            "UFG",
            "ACRV",
            "DGNX",
            "IAUX",
            "ALEC",
            "PLSE",
            "NTZ",
            "OGEN",
            "WK",
            "FKWL",
            "VIVK",
            "UMBF",
            "RANI",
            "NEM",
            "PHR",
            "BOLD",
            "PINC",
            "SENS",
            "SEPN",
            "LINC",
            "ATHR",
            "LHSW",
            "WLAC",
            "IFRX",
            "KRNT",
            "RXST",
            "BHAT",
            "JZXN",
            "INAB",
            "OFIX",
            "OST",
            "ERO",
            "JILL",
            "SIMO",
            "STAA",
            "HCM",
            "CIGL",
            "CLOV",
            "ADVB",
            "HAFN",
            "REVB",
            "RENT",
            "PRTS",
            "GRVY",
            "CRI",
            "BBGI",
            "KTTA",
            "VTRS",
            "HG",
            "WKSP",
            "GIFT",
            "BAOS",
            "IBRX",
            "JD",
            "CABO",
            "BDSX",
            "AKA",
            "IMNM",
            "PKST",
            "JDZG",
            "GME",
            "SNSE",
            "CLB",
            "BILL",
            "PLAG",
            "RIGL",
            "EVR",
            "PLX",
            "SRZN",
            "LVTX",
            "ACM",
            "NXTC",
            "ADAG",
            "NMG",
            "FLGC",
            "MAC",
            "AL",
            "AFRM",
            "ACLX",
            "SLNH",
            "IART",
            "LAB",
            "CCG",
            "APLM",
            "GLNG",
            "WELL",
            "JANX",
            "GLBS",
            "ZGN",
            "DIN",
            "LAC",
            "CRC",
            "CAAS",
            "DAC",
            "JBLU",
            "GFI",
            "ACIW",
            "WLDS",
            "JFBR",
            "CRH",
            "LEGH",
            "MARA",
            "ZSPC",
            "CMT",
            "SEMR",
            "JEF",
            "GLDG",
            "ADVB",
            "CETX",
            "SKYX",
            "RBA",
            "TTC",
            "FFIC",
            "MTVA",
            "MYSZ",
            "CCLD",
            "FBRX",
            "PATH",
            "GLBE",
            "BRC",
            "SHPH",
            "CXAI",
            "PANL",
            "CERT",
            "BAER",
            "KNOP",
            "XBIT",
            "UPB",
            "MRCC",
            "CWK",
            "AGMH",
            "TFX",
            "HCA",
            "LXRX",
            "VALN",
            "BHVN",
            "RVMD",
            "LGPS",
            "DSP",
            "HIND",
            "ASRT",
            "ROIV",
            "EPSM",
            "NPCE",
            "BPOP",
            "ARWR",
            "TROX",
            "NPB",
            "CMDB",
            "EFSI",
            "BVN",
            "EPAC",
            "GYRE",
            "SONO",
            "BFLY",
            "BDN",
            "LI",
            "EDU",
            "LVLU",
            "XHLD",
            "CVGI",
            "HCTI",
            "AII",
            "CDZI",
            "ASX",
            "SBR",
            "ALMU",
            "NREF",
            "GAIA",
            "SPHL",
            "DCGO",
            "UCTT",
            "VOC",
            "COHU",
            "CMCO",
            "RPTX",
            "FBLG",
            "FTRK",
            "FPH",
            "PLUT",
            "NAAS",
            "PACK",
            "LRMR",
            "LSF",
            "WRD",
            "ADMA",
            "TCBK",
            "CNA",
            "NTHI",
            "WFRD",
            "ICHR",
            "PRAX",
            "CLNE",
            "AHL",
            "HR",
            "XHLD",
            "IRWD",
            "PPBI",
            "NEXA",
            "CGABL",
            "NTES",
            "SHPH",
            "SNAP",
            "JTAI",
            "UPC",
            "TLYS",
            "FND",
            "UWMC",
            "NCLH",
            "SLP",
            "TGTX",
            "STRR",
            "FLOC",
            "NCT",
            "EPIX",
            "VEEE",
            "OBIO",
            "HNRG",
            "TGL",
            "TRX",
            "BODI",
            "OGN",
            "GELS",
            "KVHI",
            "KRMN",
            "LFUS",
            "TBN",
            "RVPH",
            "GM",
            "SSII",
            "THC",
            "CVE",
            "WTO",
            "VTR",
            "CDP",
            "BGM",
            "FRGT",
            "WCT",
            "TNK",
            "FG",
            "FOLD",
            "SFD",
            "S",
            "SKT",
            "CGEM",
            "LAZR",
            "IBO",
            "KNDI",
            "GLTO",
            "HCWB",
            "NX",
            "CURV",
            "TIVC",
            "DAVA",
            "ALMS",
            "USEA",
            "DVS",
            "WRD",
            "RILYT",
            "NE",
            "PPL",
            "MLCO",
            "ADAM",
            "BRIA",
            "CYH",
            "KWM",
            "GOCO",
            "CRT",
            "HCWB",
            "WRAP",
            "KYMR",
            "FOXX",
            "UTL",
            "STZ",
            "MLGO",
            "MCS",
            "TVGN",
            "TPIC",
            "JFBR",
            "TC",
            "GFS",
            "SPWR",
            "VERO",
            "FAT",
            "WTF",
            "NOMD",
            "OEC",
            "WYHG",
            "OPI",
            "LULU",
            "EVO",
            "GAP",
            "SXTC",
            "LSB",
            "UNM",
            "CGTL",
            "APVO",
            "OST",
            "CZR",
            "TW",
            "CRIS",
            "SVRE",
            "BRKR",
            "SLN",
            "NAMI",
            "RNXT",
            "BMEA",
            "JYD",
            "SNTI",
            "DMRC",
            "FIZZ",
            "TOPP",
            "OKUR",
            "HFFG",
            "TRSG",
            "DRMA",
            "GDHG",
            "CGEM",
            "OLB",
            "ILLR",
            "PTLE",
            "ACDC",
            "EDHL",
            "SYNX",
            "OMH",
            "INAB",
            "APDN",
            "SHPH",
            "WOW",
            "AZI",
            "FNKO",
            "STAK",
            "HAO",
            "GLOB",
            "MKTX",
            "EMN",
            "JZ",
            "GDHG",
            "ESTC",
            "YSXT",
            "GORV",
            "YI",
            "ANNX",
            "NMAX",
            "NVVE",
            "JCSE",
            "AZI",
            "GMHS",
            "EWCZ",
            "CSAI",
            "FLO",
            "CDRO",
            "LLY",
            "CNK",
            "IOT",
            "CWD",
            "OGN",
            "CSTE",
            "AIRI",
            "DUO",
            "AKTX",
            "SMXT",
            "EU",
            "QTTB",
            "SNOA",
            "ANNA",
            "ONON",
            "INV",
            "FBLG",
            "ADD",
            "ZDAI",
            "CMCT",
            "CNCK",
            "CLIK",
            "AREB",
            "OFAL",
            "NTCL",
            "XPOF",
            "MBIN",
            "YCBD",
            "CREG",
            "PMAX",
            "ICUI",
            "AVBP",
            "ELAB",
            "BAND",
            "PHH",
            "WKSP",
            "ABTS",
            "AMWL",
            "NIPG",
            "COCH",
            "SRL",
            "SMTK",
            "NNOX",
            "SEM",
            "LUCY",
            "GDYN",
            "DGLY",
            "SLNH",
            "IBTA",
            "CYH",
            "NGNE",
            "SUNE",
            "JSPR",
            "KUKE",
            "CETY",
            "HKPD",
            "TMDE",
            "CNEY",
            "HCAI",
            "AVIR",
            "WAT",
            "OABI",
            "MKDW",
            "DV",
            "TNMG",
            "JFBR",
            "INTS",
            "HMR",
            "NPWR",
            "HCAI",
            "ATHR",
            "SCKT",
            "GIBO",
            "DRIO",
            "WEST",
            "ARVN",
            "LVRO",
            "BTAI",
            "LOBO",
            "EDUC",
            "RENB",
            "GMM",
            "EONR",
            "IMG",
            "STEC",
            "MBRX",
            "MNDR",
            "GLXY",
            "ILLR",
            "PAVM",
            "HXHX",
            "VERA",
            "EPWK",
            "FATN",
            "XFOR",
            "SJ",
            "EHTH",
            "CSTL",
            "JAGX",
            "STKH",
            "PRGO",
            "MDCX",
            "LEE",
            "QNRX",
            "ZSPC",
            "MWYN",
            "RDNW",
            "FIEE",
            "EDBL",
            "BLMZ",
            "WOLF",
            "PWM",
            "PFAI",
            "LHSW",
            "CRWV",
            "HRL",
            "TOMZ",
            "LESL",
            "BJDX",
            "WTO",
            "GIFT",
            "BGMS",
            "ADVB",
            "YB",
            "AVNS",
            "INEO",
            "YIBO",
            "CNF",
            "SKK",
            "CRESY",
            "ATCH",
            "ICG",
            "LULU",
            "EP",
            "WORX",
            "ZSPC",
            "PACS",
            "WGRX",
            "NCNA",
            "GDDY",
            "TRNR",
            "GLTO",
            "OMSE",
            "NAAS",
            "FTRK",
            "FTRK",
            "STRZ",
            "AMOD",
            "IRDM",
            "HMR",
            "CIIT",
            "WGRX",
            "LNW",
            "NAOV",
            "SBEV",
            "CSAI",
            "KWM",
            "PMAX",
            "GVH",
            "AQMS",
            "BIYA",
            "MWYN",
            "CAVA",
            "FORM",
            "YAAS",
            "ASTL",
            "NCEW",
            "TNFA",
            "MIGI",
            "NFE",
            "MCTR",
            "EXAS",
            "MURA",
            "SDST",
            "CYCU",
            "SNPS",
            "LIMN",
            "KLC",
            "CANF",
            "INSP",
            "PPBT",
            "PUBM",
            "VCIG",
            "GIBO",
            "EDHL",
        ],
        # "selected_tickers": ["random"],  # change it to 'random' to select random stocks
        "random_count": None,
        # "min_turnover": 0,
        "plot_all": True,
        # "plot_all": False,
        "timeframe": "1d",
        "data_start_date": "2024-09-01",
        "trade_start_date": "2025-07-01",
        "end_date": "2025-09-19",
        "initial_capital": 10000.0,
    }

    strategy = BBIBOLLStrategy(config=strategy_config)

    run_backtest(strategy, strategy_config=strategy_config)

    # run_multiple_strategies_example()
